#!/bin/bash
#
# Copyright (c) 2015, Thomas Adam <thomas@xteddy.org>
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
# SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION
# OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
# CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

attach_for_tests=0
destroy_server=0

while getopts ":an" opt
do
	case "$opt" in
		a)
			attach_for_tests=1
		;;
		n)
			destroy_server=1
		;;
	esac
done

shift $(($OPTIND - 1))

ts() {
	. test_helper

	[ "$attach_for_tests" -eq 1 ] && {
		# TODO: More configuration needed:
		#			- Check $DISPLAY
		#			- Warn about $TMUX being set and prompt
		#			- x-terminal-emulator, etc., don't assume xterm.
		xterm -hold -e "$PWD/wait-for-tmux" &
	}

	command ts -r -c -s -m "$@"

	[ "$destroy_server" -eq 1 ] && {
		printf "Killing server... all done\n"
		$TMUX_BINARY kill-server
	}
}

check_for_ts()
{
	[ -d "ts" ] && {
		(cd "ts" && git pull -q 2>/dev/null)
		return 0
	}

	git clone -q https://github.com/thinkerbot/ts.git ts
}

check_for_ts

export PATH=$(pwd)/ts/bin:$PATH
ts ./*.sh
